### PR TITLE
Support for Incremental Endpoints and SideLoading

### PR DESCRIPTION
**Pull request by dkapell**
This Pull request includes:
* Support for the new incremental endpoints for Users, Organizations, Ticket Events, and Tickets
* Side Loading for almost all endpoints that support it 
* Documentation updates for the above
* A change to the way jsonAPINames are listed, to be cleaner
* A version number bump to reflect the new API bits

### CODE REVIEW

**Comment by erikzrekz** [comment]
@dkapell Haven't the time to get to this yet. Will check it out soon. @nnabuuu, any thoughts on reviewing this PR?

**Comment by nnabuuu** [comment]
Yes, I saw this PR, containing a lot of changes... I will take a look at these changes in the weekend, and try to see if we can divide it into 2

**Comment by nnabuuu** [comment]
So there are 3 changes:

Side-loading / Incremental / JSON apiName simplify

Let me check the changes one by one, here is a summary of side-loading feature that this PR supports. I'm going add these missing fields before merge. 

Name | Supported side loading | Implemented
------------ | ------------- | ---------------
Tickets | 	users, groups, organizations, last_audits, metric_sets, sharing_agreements, incident_counts, ticket_forms | Yes, but a few fields are missing
Audits |	users, organizations, groups, tickets | Yes, but a few fields are missing
Requests |	users, organizations | Yes
Users |	organizations, abilities, roles, identities, groups | Yes, but `abilities` not included
Groups |	users | Yes
Group Memberships |	users, groups | Yes
Organizations |	abilities | No
View Execution / Previewing |	The following are automatically side-loaded if applicable: group, organization, users | Automatically side-loaded
Categories (Help Center) |	translations | No
Sections (Help Center) |	categories, translations | No
Articles (Help Center) |	users, sections, categories, translations | No
Article comments (Help Center) |	users, articles, translations | No
Subscriptions (Help Center) |	users, articles, sections | No
Votes (Help Center) |	users, articles, translations | No

**Comment by nnabuuu** [comment]
Hi @dkapell , thank you for your commit, I am still on the way of implementing side-loading for help-center and will get this PR merged as soon as it completes. The progress is delayed just because the side-loading format in core api and help-center api are too different : (

**Comment by nnabuuu** [comment]
Finally get all these merged.. Thanks @dkapell

**Pull request merged**
