### PR TITLE
feat: .d.ts types and client restructure

### PR DESCRIPTION
**Pull request by onhate**
## Pull Request Description

- Setup Github Actions to always run tests on each commit;
- Setup Github Actions to auto generate release drafts https://github.com/release-drafter/release-drafter
- Generate `.d.ts` files when publishing the package to npmjs;
- Restructure the client so we can have strongly typed client properties (client.tickets, client.organization...);
- Moved services, nps, voice and helpcenter to specific client namespaces to avoid method conflicts (`this.search` and `this.helpercenter.search`)
- Introduced `cross-fetch` instead of nodejs native fetch so it works both on browser and nodejs eco systems and also  allow tests to pass as we use nock of it see https://github.com/nock/nock/issues/2397
- Re-generated the client jsdocs to generate correct types (still pending to generate service specific types, on coming PRs)
- Now each service is responsible to pass a second arg param to the super class `Client` telling the `ApiType` it is, based on that the `Client` class can build the `endpointUri`, for example:

```js
class AccessPolicies extends Client {
  constructor(options) {
    //  HERE you should pass the api type to super Client constructor, ApiTypes.core is the default value
    super(options, ApiTypes.helpcenter);
    this.jsonAPINames = ['accesspplicies', 'accesspolicy'];
  }
...
```
then the `Client` will use this `apiType` to build the URL

```js
  _getEndpointUri(subdomain, apiType) {
    const endpoint = Endpoints[apiType];
    return `https://${subdomain}${endpoint}`;
  }
```

this is on constants

```js
/**
 * @readonly
 * @enum {string}
 */
const ApiTypes = {
  core: 'core',
  helpcenter: 'helpcenter',
  services: 'services',
  voice: 'voice',
  nps: 'nps'
};


/**
 * @readonly
 * @type {Record<ApiTypes, string>}
 */
const Endpoints = {
  core: '.zendesk.com/api/v2',
  nps: '.zendesk.com/api/v2/nps', // TODO ????
  helpcenter: '.zendesk.com/api/v2/help_center',
  services: '.zendesk.com/api/services/jira',
  voice: '.zendesk.com/api/v2/channels/voice',
};
```

---

## Related Issue(s)

- [X] This PR fixes/closes issue https://github.com/blakmatrix/node-zendesk/issues/331

---

## Additional Information

- [X] This change is a breaking change (may require a major version update)
  -  Only for nps, services, helpcenter and voice, core services should still work the same.
- [ ] This change is a new feature (non-breaking change which adds functionality)
- [X] This change improves the code (e.g., refactoring, etc.)
- [X] This change includes dependency updates

---

## Test Cases

All test cases should still work as expected.

---

## Documentation

- [ ] I have updated the documentation accordingly.
- [X] No updates are required.

---

## Checklist

- [X] I have read the [CONTRIBUTING](./CONTRIBUTING.md) documentation.
- [X] My code follows the coding standards of this project.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by onhate** [comment]
`index.d.ts` sample generated from `npm run build` command

```ts
export type ZendeskClientOptions = {
    name: string;
    /**
     * - The username used for authentication.
     */
    username: string;
    /**
     * - The authentication token.
     */
    token: string;
    /**
     * - The subdomain for the Zendesk account (e.g., 'mycompany' for 'mycompany.zendesk.com').
     * If the `endpointUri` option is provided, `subdomain` will be ignored and the logic
     * to manage multi-type endpoints will be disabled.
     */
    subdomain?: string;
    /**
     * - Type of Zendesk API to initialize (e.g., 'core', 'helpcenter').
     * Determines which sub-client to use.
     */
    apiType?: string[];
    /**
     * - The base URI for the Zendesk API. Overrides and ignores `subdomain` if provided.
     */
    endpointUri?: string;
    /**
     * - Function to get specific options. By default, accesses property from the options.
     */
    get?: Function;
    /**
     * - Flag to indicate if OAuth is used.
     */
    oauth?: boolean;
    /**
     * - Optional header for making requests on behalf of a user.
     */
    asUser?: string;
    /**
     * - Any additional custom headers for the request.
     */
    customHeaders?: object;
    /**
     * - Flag to enable throttling of requests.
     */
    throttle?: boolean;
    /**
     * - Flag to enable or disable debug logging.
     */
    debug?: boolean;
    /**
     * - Optional logger for logging. Should have methods like `info`, `error`, etc. Defaults to a basic console logger.
     */
    logger?: object;
    /**
     * - Configuration for custom transport functionality.
     */
    transportConfig?: {
        transportFn?: Function;
        responseAdapter?: Function;
    };
};
/**
 * @function createClient
 * @param {ZendeskClientOptions} options
 * @return {ZendeskClient}
 */
export function createClient(options: ZendeskClientOptions): ZendeskClient;
/**
 * @typedef {Object} ZendeskClientOptions
 * @property {string} ZendeskClientOptions.name
 * @property {string} ZendeskClientOptions.username - The username used for authentication.
 * @property {string} ZendeskClientOptions.token - The authentication token.
 * @property {string} [ZendeskClientOptions.subdomain] - The subdomain for the Zendesk account (e.g., 'mycompany' for 'mycompany.zendesk.com').
 *                                     If the `endpointUri` option is provided, `subdomain` will be ignored and the logic
 *                                     to manage multi-type endpoints will be disabled.
 * @property {string[]} [ZendeskClientOptions.apiType=['core']] - Type of Zendesk API to initialize (e.g., 'core', 'helpcenter').
 *                                    Determines which sub-client to use.
 * @property {string} [ZendeskClientOptions.endpointUri] - The base URI for the Zendesk API. Overrides and ignores `subdomain` if provided.
 * @property {function} [ZendeskClientOptions.get] - Function to get specific options. By default, accesses property from the options.
 * @property {boolean} [ZendeskClientOptions.oauth] - Flag to indicate if OAuth is used.
 * @property {string} [ZendeskClientOptions.asUser] - Optional header for making requests on behalf of a user.
 * @property {object} [ZendeskClientOptions.customHeaders] - Any additional custom headers for the request.
 * @property {boolean} [ZendeskClientOptions.throttle] - Flag to enable throttling of requests.
 * @property {boolean} [ZendeskClientOptions.debug=false] - Flag to enable or disable debug logging.
 * @property {object} [ZendeskClientOptions.logger=ConsoleLogger] - Optional logger for logging. Should have methods like `info`, `error`, etc. Defaults to a basic console logger.
 * @property {object} [ZendeskClientOptions.transportConfig] - Configuration for custom transport functionality.
 * @property {function} [ZendeskClientOptions.transportConfig.transportFn] - Custom function to perform the request. By default, it uses `fetch`. It should return a response object.
 * @property {function} [ZendeskClientOptions.transportConfig.responseAdapter] - Custom function to adapt the response from `transportFn` into a consistent format. By default, it adapts for `fetch` response.
 */
/**
 * Represents the main client to interface with the Zendesk API.
 * This class acts as a high-level interface, making it easier to interact with specific Zendesk APIs.
 *
 * @class
 * @property {ZendeskClientOptions} config - Configuration options for the client.
 * @property {ConsoleLogger} logger - Logger for logging.
 */
declare class ZendeskClient {
    /**
     * @constructs ZendeskClient
     * @param {ZendeskClientOptions} options - Configuration options for the client.
     * @example
     * const zendeskOptions = {
     *     username: 'exampleUser',
     *     token: 'exampleToken',
     *     subdomain: 'mycompany'
     * };
     * const zendeskClient = createClient(zendeskOptions);
     * const data = await zendeskClient.someResource.someMethod();
     */
    constructor(options?: ZendeskClientOptions);
    config: ZendeskClientOptions;
    logger: any;
    helpcenter: ZendeskClientHelpcenter;
    services: ZendeskClientServices;
    voice: ZendeskClientVoice;
    nps: ZendeskClientNps;
    /**
     * @template {T} [T=import('./client/client.js').Client]
     * @param {{ new (options: ZendeskClientOptions): T }} clazz
     * @return {T}
     * @private
     */
    private _instantiate;
    /**
     * @private
     */
    private instances;
    get accountsettings(): import("./clients/core/accountsettings").AccountSettings;
    get activitystream(): import("./clients/core/activitystream").ActivityStream;
    get attachments(): import("./clients/core/attachments").Attachments;
    get automations(): import("./clients/core/automations").Automations;
    get brand(): import("./clients/core/brand").Brand;
    get customagentroles(): import("./clients/core/customagentroles").CustomAgentRoles;
    get dynamiccontent(): import("./clients/core/dynamiccontent").DynamicContent;
    get dynamiccontentvariants(): import("./clients/core/dynamiccontentvariants").DynamicContentVariants;
    get groupmemberships(): import("./clients/core/groupmemberships").GroupMemberships;
    get groups(): import("./clients/core/groups").Groups;
    get imports(): import("./clients/core/imports").Imports;
    get installations(): import("./clients/core/installations").Installations;
    get jobstatuses(): import("./clients/core/jobstatuses").JobStatuses;
    get locales(): import("./clients/core/locales").Locales;
    get macros(): import("./clients/core/macros").Macros;
    get oauthtokens(): import("./clients/core/oauthtokens").OauthTokens;
    get organizationfields(): import("./clients/core/organizationfields").OrganizationFields;
    get organizationmemberships(): import("./clients/core/organizationmemberships").OrganizationMemberships;
    get organizations(): import("./clients/core/organizations").Organizations;
    get permissiongroups(): import("./clients/core/permissiongroups").PermissionGroups;
    get policies(): import("./clients/core/policies").Policies;
    get requests(): import("./clients/core/requests").Requests;
    get satisfactionratings(): import("./clients/core/satisfactionratings").SatisfactionRatings;
    get search(): import("./clients/core/search").Search;
    get sessions(): import("./clients/core/sessions").Sessions;
    get sharingagreement(): import("./clients/core/sharingagreement").SharingAgreement;
    get suspendedtickets(): import("./clients/core/suspendedtickets").SuspendedTickets;
    get tags(): import("./clients/core/tags").Tags;
    get targets(): import("./clients/core/targets").Targets;
    get ticketaudits(): import("./clients/core/ticketaudits").TicketAudits;
    get ticketevents(): import("./clients/core/ticketevents").TicketEvents;
    get ticketexport(): import("./clients/core/ticketexport").TicketExport;
    get ticketfields(): import("./clients/core/ticketfields").TicketFields;
    get ticketforms(): import("./clients/core/ticketforms").TicketForms;
    get ticketimport(): import("./clients/core/ticketimport").TicketImport;
    get ticketmetrics(): import("./clients/core/ticketmetrics").TicketMetrics;
    get tickets(): import("./clients/core/tickets").Tickets;
    get triggers(): import("./clients/core/triggers").Triggers;
    get userfields(): import("./clients/core/userfields").UserFields;
    get useridentities(): import("./clients/core/useridentities").UserIdentities;
    get users(): import("./clients/core/users").Users;
    get views(): import("./clients/core/views").Views;
    get webhooks(): import("./clients/core/webhooks").Webhooks;
    get agentactivity(): import("./clients/voice/agentactivity").AgentActivity;
    get availabilities(): import("./clients/voice/availabilities").Availabilities;
    /**
     * @private
     */
    private _debug;
}
import { ZendeskClientHelpcenter } from "./clients/helpcenter";
import { ZendeskClientServices } from "./clients/services";
import { ZendeskClientVoice } from "./clients/voice";
import { ZendeskClientNps } from "./clients/nps";
export {};
```

**Comment by onhate** [comment]
P.S.: I am already using this version of the lib on our systems here and it is still working as previously it was, but the difference is that types are matching the code.

**Comment by onhate** [comment]
@blakmatrix if you would like to go through this changes on a session let me know, I would like to discuss with you some ideas for this lib.

**Comment by blakmatrix** [comment]
Wow, just red through the PR, pretty comprehensive and through work, I'd love to hop on a session and discuss

**Comment by blakmatrix** [comment]
@onhate I was checking out the repo, and I decided to see if I could call jsdoc on it and ran into some issues... granted I'm not to fluent on types but it appeared jsdoc2md didn't like this part in `src/index.js`?

```jsdoc
  /**
   * @template {T} [T=import('./client/client.js').Client]
   * @param {{ new (options: ZendeskClientOptions): T }} ServiceClass
   * @return {T}
   * @private
   */
```

the error:

```
JSDOC_ERROR: ERROR: Unable to parse a tag's type expression for source file /home/blakmatrix/projects/test/node-zendesk/src/index.js in line 63 with tag title "param" and text "{{ new (options: ZendeskClientOptions): T }} ServiceClass": Invalid type expression "{ new (options: ZendeskClientOptions): T }": Expected ",", ":", or "}" but "(" found.
ERROR: Unable to parse a tag's type expression for source file /home/blakmatrix/projects/test/node-zendesk/src/index.js in line 69 with tag title "param" and text "{{ new (options: ZendeskClientOptions): T }} ServiceClass": Invalid type expression "{ new (options: ZendeskClientOptions): T }": Expected ",", ":", or "}" but "(" found.
```

I played around with some things and was able to change it to and then jsdoc2md put out correctly... I guess my question is is this correct or by removing the imports is it breaking something?

```jsdoc
/**
 * @typedef {Object} ServiceClassType
 * @template T
 * @property {function(new:T, ZendeskClientOptions)} constructorFn
 */

 /**
   * @template T
   * @param {ServiceClassType<T>} ServiceClass
   * @return {T}
   * @private
   */
  _instantiate(ServiceClass) { ... }
```

I also added the I also added the `[T=import('./client/client.js').Client]` part back to the `@typedef {Object} ServiceClassType` and it didn't throw an error either... the only reason I'm asking was I was hoping to be able to run a jsdoc2md  tool to autogenerate some on the api docs i've been planning and I'm not too familiar with jsdoc types and the imports and stuff

**Review by blakmatrix — APPROVED** [review]
Looks great! I'll be merging it soon! @onhate thanks for all your contributions

**Pull request merged**
