### PR TITLE
feat: side conversations

### PR DESCRIPTION
**Pull request by onhate**
## Pull Request Description

Ticket Side Conversations API 
https://developer.zendesk.com/api-reference/ticketing/side_conversation/side_conversation/

---

## Related Issue(s)

- [ ] This PR fixes/closes issue #...
- [X] This is a new feature and does not have an associated issue.

### CODE REVIEW

**Comment by blakmatrix** [comment]
Let me know when you are ready to checkin @onhate

**Comment by onhate** [comment]
@blakmatrix the main methods for the side conversation are done, I've tested it my application and it creates the side conversations and lists them.

**Comment by onhate** [comment]
I'm using copilot chat to generate the types, I basically copy the doc text like bellow and paste on the chat asking to generate jsdocs, that speeds up the process


2023-12-27T11-25-30

**Comment by onhate** [comment]
@blakmatrix ready to review

**Review by blakmatrix — APPROVED** [review]
LGTM Thanks!

**Comment by blakmatrix** [comment]
@onhate Looks like there is an issue with resolving a few things here... I didn't see it until I tried to compile the docs:

```sh
❯ npm run docs:code

> node-zendesk@5.0.8 docs:code
> npx typedoc --out ./docs/code --plugin typedoc-plugin-markdown 'dist/**/*.ts'

[info] Loaded plugin typedoc-plugin-markdown
dist/types/clients/core/sideconversations.d.ts:296:23 - error TS2304: Cannot find name 'Ticket'.

296         result: Array<Ticket>;
                          ~~~~~~

dist/types/clients/core/tickets.d.ts:601:20 - error TS2304: Cannot find name 'CreateOrUpdateTicket'.

601     create(ticket: CreateOrUpdateTicket): Promise<{
                       ~~~~~~~~~~~~~~~~~~~~

dist/types/clients/core/tickets.d.ts:619:31 - error TS2304: Cannot find name 'CreateOrUpdateTicket'.

619     createMany(tickets: Array<CreateOrUpdateTicket>): Promise<Array<Ticket>>;
                                  ~~~~~~~~~~~~~~~~~~~~

dist/types/clients/core/tickets.d.ts:636:38 - error TS2304: Cannot find name 'CreateOrUpdateTicket'.

636     update(ticketId: number, ticket: CreateOrUpdateTicket): Promise<{
```

**Comment by onhate** [comment]
hi @blakmatrix , let me check

**Pull request merged**
