### PR TITLE
Tickets list using filter

### PR DESCRIPTION
**Pull request by karolisg**

### CODE REVIEW

**Comment by erikzrekz** [comment]
@karolisg this won't work when using the method `requestAll` since it will begin paginating. So on my first request of tickets I get `/api/v2/tickets.json?id=123` but then I begin getting `/api/v2/tickets.json?page=2` and then `/api/v2/tickets.json?page=3` etc. 

Want to take another stab at it?

**Comment by karolisg** [comment]
@erikzrekz I fixed this issue. Now pagination works perfectly.

**Comment by erikzrekz** [comment]
@karolisg awesome. Will take a look. Thanks!

**Comment by erikzrekz** [comment]
@karolisg looks good. I'll be including this in v1.1.9 - https://slack-files.com/T04LRT0NA-F0VNC4PL0-27e43520b3

**Comment by erikzrekz** [comment]
Thanks!

**Pull request merged**
