### PR TITLE
Add create-or-update user endpoints

### PR DESCRIPTION
**Pull request by andygeers**
Gives access to the create_or_update endpoints

### CODE REVIEW

**Comment by RaFeNiX** [comment]
I was looking for this update too, hope he confirms his e-mai lsoon ;)

**Comment by erikzrekz** [comment]
@andygeers this looks good. Thanks for doing this. Would you mind holding off on bumping the version number though? There are some more updates that I want to get in v1.1.9

**Comment by erikzrekz** [comment]
@andygeers this will be in v1.1.9. Here are the pre-release notes - https://slack-files.com/T04LRT0NA-F0VNC4PL0-27e43520b3

**Comment by erikzrekz** [comment]
Thanks!

**Pull request merged**
