### PR TITLE
add organization memberships as CBP default

### PR DESCRIPTION
**Pull request by cryptomail**
add organization memberships as CBP default.  Updated documentation at Zendesk.
@blakmatrix for your consideration.

### CODE REVIEW

**Comment by cryptomail** [comment]
hold on let me make a branch....and I need more syncing commits :)

**Comment by cryptomail** [comment]
ok reopened this one

**Review by blakmatrix — APPROVED** [review]
@cryptomail LGTM, let me know if it's all good to go or if there are more changes you want to add. Thanks again 🙏

**Comment by cryptomail** [comment]
> @cryptomail LGTM, let me know if it's all good to go or if there are more changes you want to add. Thanks again 🙏

@blakmatrix Yeap this one in particular is Good To Go :)
There will be more, but we're sharing more of the endpoints later.  Incrementally shoring up this last remaining bit for the Support domain will be awesome, and in an additional PR, we'll shore up the HC ones!!

Thank you for merging, and bumping!!! <3

**Pull request merged**
