### PR TITLE
chore: remove dynamic imports

### PR DESCRIPTION
**Pull request by onhate**
## Pull Request Description

Removing dynamic requires to enable using bundlers, this will allow running on AWS Lambda and even on the browser.

---

## Related Issue(s)

- [x] This PR fixes/closes issue https://github.com/blakmatrix/node-zendesk/issues/282

---

## Additional Information

- [ ] This change is a breaking change (may require a major version update)
- [ ] This change is a new feature (non-breaking change which adds functionality)
- [X] This change improves the code (e.g., refactoring, etc.)
- [ ] This change includes dependency updates

---

## Test Cases

All tests are the same and should pass as normal

---

## Documentation

- [ ] I have updated the documentation accordingly.
- [X] No updates are required.

---

## Checklist

- [X] I have read the [CONTRIBUTING](./CONTRIBUTING.md) documentation.
- [X] My code follows the coding standards of this project.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by onhate** [comment]
@blakmatrix what do you think? This is pretty important to enable bundling of apps.

**Comment by blakmatrix** [comment]
@onhate Thank you so much I've been trying to figure this one out for a bit now, just confirmed it also works with esbuild... smallest gzip file I could make is 17kb ...

Do you know how to make tree shaking work with this library?

**Comment by blakmatrix** [comment]
closes #324 as well

**Comment by onhate** [comment]
thanks @blakmatrix for the quick responses and for merging this PR.

to make a package tree-shakable it's required to export each class independently (not instances), because if you export instances the compiler treats it as `PURE CODE` which means it should be executed, but if you export just the classes it can ignore the rest as it knows it will not need to be executed.

So the client design will need to change from a client with all instances inside it like we have now, to something like this:

```js
import { createClient, Tickets, Users } from 'node-zendesk';

const client = createClient(...);

const tickets = new Tickets(client);
const usets = new Users(client);
```

As you can see, if you don't use the other classes the bundler will tree-shake them out of the final bundle and import only the Ticket, Users and createClient stuff and dependencies each has.

**Pull request merged**
