### PR TITLE
Adding Promise support

### LINKED ISSUE #202: Promise Support
Promises are the standard modern way to deal with asynchrony in JavaScript. It would be useful to have first-class Promise support in `node-zendesk`.

This is a dupe of #156, which was closed without explanation.

### PR DESCRIPTION
**Pull request by fmsouza**
* Returns Node.js native `Promises` in every API call when a callback is not given
* Retrocompatible
* Removes unused imports
* Added some examples of calls using the new `Promise` alternative

Closes #202.

### CODE REVIEW

**Comment by magic-madrigal** [comment]
+1

**Comment by MichielDeMey** [comment]
What about backward compatibility?
Is it a breaking change? If so, we'll need to release a new major version (2.x.x).

**Comment by maddox** [comment]
I tried this branch while using Help Center endpoints and all I got returned from the promise was the `HTTP` status code :/

**Comment by fmsouza** [comment]
@MichielDeMey it's not supposed to be a breaking change. My intention was to keep it working the way it is, as long as giving the Promise way as a new feature.

And yes, @maddox. I noticed that a couple months ago because I published a fork of this lib for my internal usage, and noticed I was having this issue with all the methods which relies on `requestAll`. The logic there is sort of confusing, so I need to take a look again in order to guarantee it will be backwards compatible while adding the Promise support.

The problem is I have been quite busy lately, as you can see by the delay between messages. I'll try to check it again this week to fix this PR. I really hope I can find some time for that ASAP.

**Comment by ajmueller** [comment]
@fmsouza I know it's been awhile, so chances are you had to move on from this, but is there any chance that this is something you're still hoping to work on?  My company just started using Zendesk and Promise support would be a fantastic addition.  In the meantime I'm using Node's custom promisify util to make it work with Promises, but it's definitely not ideal.

**Comment by fmsouza** [comment]
@ajmueller by the time I stopped working on this PR I created an internal package which implements the requests from the scratch for the company I used to work for. However, I might need to work on Zendesk integration once again for another project, and so I might revisit that and attempt to get this PR completely working. I'll take a look that once again asap.

**Comment by fmsouza** [comment]
I just fixed the conflicts with `master` and fixed what I believe could be the problem with the `this.requestAll` method on my PR, but it needs a bit more of testing. @maddox would you be up to give it a try again in your use case and tell us if it's ok now?

@ajmueller do your usage involves any operations using `this.requestAll` so you could give it a try and let us know if it's working now?

**Comment by joltcoke** [comment]
> @ajmueller do your usage involves any operations using `this.requestAll` so you could give it a try and let us know if it's working now?

@fmsouza Calling await client.tickets.getComments(ticketId) (which internally calls requestAll) still seems broken. If I understood the code correctly, the problem is this line:

https://github.com/fmsouza/node-zendesk/blob/36b51408fd86b26a4a9dc401c259b98eacd28639/lib/client/client.js#L187

completeCb(statusList, flatten(bodyList), responseList, resultList) will end up in resolve(statusList) discarding 3 out of 4 parameters.

**Comment by fmsouza** [comment]
@joltcoke yes, it does make sense. But what is the problem you are experiencing when you run this command?

About the spec, `Promise.resolve()` will always return a single value. So it won't be possible to keep the same API as we have in the callbacks right now in the Promise. However, it's possible to destructure the results so I can keep all the results in the final response. It could look either:
```
const [statusList, flatBodyList, responseList, resultList] = await client.tickets.getComments(ticketId);
```
or
```
const { statusList, flatBodyList, responseList, resultList } = await client.tickets.getComments(ticketId);
```
What would you rather use in this case?

**Comment by joltcoke** [comment]
The actual problem with the current PR is that you only have access to statusList. 

I'm new to the Zendesk world so maybe I've yet to fully understand the API and the specifics of the nodeJS implementation, but in general I would expect that if the API succeeds I get the body (and just the body). No additional magic necessary to extract the information I'm looking for.

If the API (for whatever reason) fails, I'm expecting the call to throw an exception.

So I would prefer:

try {
const flatBodyList = await client.tickets.getComments(ticketId);
} catch (status) {
}

**Comment by joltcoke** [comment]
@fmsouza I've created https://github.com/fmsouza/node-zendesk/pull/2 to quick fix requestAll(). Returning bodyList is certainly the better options than to return statusList.

**Comment by fmsouza** [comment]
Thank you @joltcoke! I was going to do the exact same thing, but didn't had time to even check it again. 😄

**Comment by ajmueller** [comment]
@fmsouza my apologies for the delay on responding to your request over a month ago.  I just tested your fork and had a mix of success and some errors.  We're only using the library to create tickets, so our usage is pretty limited.  Here's what I saw:

1. Creating the ticket in Zendesk worked as expected.  It was added to our Agents' lists with the content we wanted.  However...
2. ...the value of `createdTicket` in `const createdTicket = await zendeskClient.tickets.create(ticket);` was `undefined`.  I was expecting the Promise to resolve to the ticket body based on what I saw in @joltcoke's PR in your fork.
3. I'm seeing the below error in my Node console:

```bash
/opt/app/node_modules/node-zendesk/lib/client/client.js:291
return callback(null, response.statusCode, body, response, res);
       ^

TypeError: callback is not a function
at /opt/app/node_modules/node-zendesk/lib/client/client.js:291:12
at checkRequestResponse (/opt/app/node_modules/node-zendesk/lib/client/client.js:258:10)
at requestCallback (/opt/app/node_modules/node-zendesk/lib/client/client.js:266:3)
at Request._callback (/opt/app/node_modules/node-zendesk/lib/client/client.js:111:5)
at Request.self.callback (/opt/app/node_modules/request/request.js:185:22)
at Request.emit (events.js:196:13)
at Request.EventEmitter.emit (domain.js:471:20)
at Request.<anonymous> (/opt/app/node_modules/request/request.js:1161:10)
at Request.emit (events.js:196:13)
at Request.EventEmitter.emit (domain.js:471:20)
at IncomingMessage.<anonymous> (/opt/app/node_modules/request/request.js:1083:12)
at Object.onceWrapper (events.js:284:20)
at IncomingMessage.emit (events.js:201:15)
at IncomingMessage.EventEmitter.emit (domain.js:471:20)
at endReadableNT (_stream_readable.js:1130:12)
at processTicksAndRejections (internal/process/task_queues.js:84:9)
```

**Comment by fmsouza** [comment]
@ajmueller I just modified the `examples/ticket-create.js` testing script to resolve with promises instead and noticed it's returning the full response instead of only the body for this same operation. I'm checking it right now to make it return the body instead.

**Comment by fmsouza** [comment]
@ajmueller could you please test again right now? I believe I might have fixed the issue.

There are also some new examples for creating tickets with the promisified version (`examples/ticket-create-promise.js`) and creating a new user (`examples/user-create-promise.js`).

I just tested with a trial account I got access earlier today and it seems to be working fine. I can either see the entities being successfully created in the panel and receive the correct response on the app.

**Comment by fmsouza** [comment]
@ajmueller @blakmatrix any updates here? :)

**Comment by fmsouza** [comment]
Guys, can someone please check that and give input if it's okay now? My last update to the PR was 2 months ago and I got no updates since then...

**Comment by ajmueller** [comment]
@fmsouza sorry for the delay.  In the last couple months I've been swamped working on a re-platforming of my company's main application to React and haven't had much time to look into other things.  Now with the spread of COVID-19, we're struggling like many other businesses to keep things going.

I'll see if I can whip up a quick test soon.

**Comment by ajmueller** [comment]
@fmsouza I just tested the creation of a ticket with a basic Express app and Postman and it worked great!  The response from `await zendeskClient.tickets.create()` was the ticket body, as expected.

image


image

**Comment by mpalavrov** [comment]
@fmsouza, thank you for editing this library. It is not working very good when adding the Promise (asnyc) functionality. I hope it is verified by more persons soon and merged in the original one.

**Comment by blakmatrix** [comment]
@fmsouza Looks like folks are happy with this feature, hope you are well during these times. **If you could massage the conflicts out I will be happy to push this PR through**, Thank you for all your time for supporting the open-source community and for you being you :)

May you be Happy!
May you be Healthy!
May you be Safe!
May you be at Peace!
May you be Loved!

**Comment by fmsouza** [comment]
@blakmatrix thank you very much for the warmful message! I'm really glad to help. I've just merged the latest changes on `master` and resolved the conflicts. Let me know if there's anything else I can do.

Stay safe and in peace you too!

**Pull request merged**
