### PR TITLE
Fixed Bug and 2 new Feature (Import and Export of tickets)

### PR DESCRIPTION
**Pull request by davidearlotto**
Fixed Revert on Client.js
Added Import function (ticketimport.js)
Added Incremental Export for tickets (ticketexport.js)

### CODE REVIEW

**Comment by blakmatrix** [comment]
:+1:

**Comment by erikzrekz** [comment]
Hey @davidearlotto, this looks good. What do you mean by fixed revert on client.js? I don't see that in this PR.

**Comment by davidearlotto** [comment]
Hi @erikzrekz. It was for me, last time I pushed client.js was fucked. 
Nothing changed though this time.

**Comment by erikzrekz** [comment]
@davidearlotto got it. Thanks.

**Pull request merged**
